export var define = {
"abase":"to reduce or lower; to humble or cast down",
"abated":"diminished in intensity or amount; lessened",
"abba":"father; a superior (Chaldee/Syriac)",
"abhor":"to shrink from with dread; lothe, detest",
"abjects":"an outcast, a worthless, despicable person .",
"abroad":"outdoors; away from home; scattered about",
"adamant":"a sharp, hard stone; hardest substance",
"adjure":"to charge or bind by an oath or threat",
"admiration":"wonder or astonishment",
"admonish":"to instruct; warn; reprove mildly",
"ado":"trouble; labor; fuss",
"adventure":"hazard, risk",
"advertise":"give notice, inform",
"advisement":"a consultation; counsel",
"affect":"to act upon; embitter; desire, seek",
"affinity":"a relationship by marriage",
"affording":"accomplishing, yielding, producing or providing",
"afoot":"to go on foot; walk",
"afore":"before; prior",
"agone":"past, ago",
"ague":"fever; chill",
"albeit":"although; even though",
"alleluia":"praise the lord",
"alms":"charity; relief to the poor",
"amazed":"Astonished; confounded with fear, surprise or wonder",
"ambassage":"ambassadors, delegation",
"amerce":"to punish by imposing a penalty or fine",
"amiable":"friendly, agreeable, or lovely",
"amiss":"in error, incorrect, improper",
"anathema":"excommunication with a curse",
"ancient":"old person yet still alive, elders",
"angle":"fishing rod with hook",
"anise":"an herb of the parsley family",
"anon":"immediately, at once",
"apace":"traveling at a great pace, swiftly",
"apostle":"messenger; one sent on a mission",
"apothecary":"a store or shop; pharmacy, spice dealer",
"apparel":"clothing; attire",
"appertain":"belong or pertain to",
"aright":"correctly, properly",
"armholes":"the armpit; the hole in the garment in which the arm is put",
"array":"To clothe; to line up an army for battle",
"artificer":"one who makes something by art or skill",
"artillery":"offensive weapon such as a bow or sling",
"asp":"a snake, serpent",
"assay":"to try, undertake, prove, or attempt",
"assent":"to agree, concur",
"asswage":"to lessen, relieve, or ease",
"astonied":"astonished, surprised or startled",
"asunder":"apart; into parts; separately",
"attent":"to be attentive, observant",
"augment":"to enlarge, increase, or supplement",
"austere":"to be severe, strict, harsh",
"averse":"to be opposed, unwilling, disinclined, turned back",
"avouched":"guaranteed, admitted, affirmed, or vouched for",
"away with":"tolerate, bear, and endure; to take away",
"axletrees":"wooden axels, spindle",
"backbiting":"to slander; to attack one's character",
"bakemeats":"baked food",
"bank":"mound for besieging a city",
"banqueting":"a feast; drinking party",
"barbarian":"foreigner, alien",
"barked":"to have the bark scrapped off",
"base":"lowly, humble",
"bastard":"an illegitimate child",
"bath":"about 8 gallons of liquid",
"battlement":"a formation on top of a wall for protection",
"beckoned":"to make a signal or to summon",
"bedstead":"a place for a bed; bed frame",
"beeves":"the plural of beef, oxen",
"begat":"to get, bear or bring forth",
"beggarly":"a beggar, indigent, poverty stricken",
"begotten":"procreated; brought forth",
"behemoth":"a beast or brute; large animal",
"behoved":"requirement; necessary",
"belied":"to deceive by lying, assert falsely, prove to be false",
"bemoan":"bewail, lament, or express pity for",
"beseech":"to seek; call upon",
"besom":"broom; sweeping tool",
"bestead":"distressed; perplexed",
"bestir":"to heap up, to stir up",
"bethink":"to remember, remind",
"betimes":"early, in due time",
"betrothed":"contracted for future marriage; engaged",
"bettered":"improve, amended, render more excellent",
"betwixt":"in between",
"bewail":"to express sorrow, lament, mourn",
"bewitched":"to fascinate; charm",
"bewray":"to reveal, expose, disclose, or betray",
"bier":"a frame on which a corpse or casket is laid",
"billow":"a swelling of water",
"bishop":"overseer",
"bishoprick":"the office of Bishop or overseer",
"bittern":"a bird similar to a heron",
"blains":"an swelling or sore; a boil",
"blaze":"to make known, proclaim, sound an alarm or publish",
"blueness":"the mark of a bruise",
"boisterous":"strong; mighty; powerful",
"bolled":"to be swollen or inflated; full seed pods",
"bolster":"a pillow or cushion used as a means of support",
"bondslave":"a peasant or someone in slavery",
"bosses":"ornamental knobs",
"botch":"ulcer, tumor, boil",
"bowels":"the interior of anything, affections",
"bravery":"splendor; magnificence",
"bray":"to crush; to cry out",
"breeches":"garments for the loins and thighs",
"brigandine":"body armor",
"brimstone":"burning stone of sulphur",
"broided":"braided",
"broidered":"to embroider or ornament with needlework",
"bruit":"rumor, report",
"brutish":"uncivilized, stupid, slow, or without understanding",
"buckler":"a round shield with a grip",
"buffet":"strike, beat, or contend against",
"bulrush":"a tall aquatic plant or a cattail",
"bunches":"a hump, bump, swelling or tumor",
"butler":"cup-bearer",
"by and by":"immediately or at once",
"cab":"nearly 4 pints",
"calve":"an animal giving birth to a calf",
"canker":"a sore, ulcer, or malignant growth",
"cankered":"eaten away",
"carbuncle":"red precious stone",
"careful":"anxious;",
"carefulness":"anxiety",
"careless":"free from care, secure",
"carnal":"sensual, fleshly, worldly",
"carriage":"that which is carried",
"castaway":"rejected",
"caul":"fatty tissue that surrounds an organ in the body",
"causeway":"paved highway",
"ceiled":"covered, panelled",
"chambering":"sexual indulgence or lewdness",
"chamberlain":"manager of a household or town",
"chamois":"a small antelope",
"champaign":"a plain; flat, open country",
"chapiter":"head of, or capital of a column",
"chapmen":"a merchant, peddler, or businessman",
"chapt":"cracked",
"charger":"a platter or large dish",
"charity":"love, affection",
"chaste":"pure from sexual commerce; undefiled",
"chasten":"to correct by punishment; to punish",
"check":"repulse, rebuke",
"chide":"to quarrel, contend, strive or argue",
"chode":"complained",
"choler":"anger, wrath, or irascibility",
"churl":"a rude or coarse man",
"circumspect":"to be cautious, wary, or discreet",
"cleave":"to split or divide;  to cling or adhere to",
"clift":"cleft, hollow",
"closet":"private room",
"clouts":"a piece of cloth, often used as a patch",
"coasts":"borders, region",
"cockatrice":"a serpent",
"cockle":"a weed, darnel, or tares",
"coffer":"a chest, box, trunk or coffin",
"cogitations":"to think, reflect, consider, or meditate",
"collops":"a small piece or slice of flesh",
"comeliness":"becoming, fit or suitable",
"comely":"fair, pleasing, appropriate",
"comfort":"To strengthen; to invigorate; to cheer or enliven",
"comforted":"To strengthen; to invigorate; to cheer or enliven",
"commodious":"to be profitable, suitable, beneficial",
"communicate":"to impart; to give to another",
"companied":"accompanied",
"compass":"to go around, surround, or encircle",
"conceit":"opinion, conception",
"concision":"a cutting; cut to pieces",
"concluded":"included",
"concord":"in agreement, harmony, accord",
"concourse":"an assembly of people or a crowd",
"concubine":"a wife of inferior condition",
"concupiscence":"strong desire or appetite",
"coney":"a small, rabbit like, nocturnal animal",
"confection":"a composition or mixture",
"confederate":"a league or joined together",
"constrain":"to compel, force, or strongly encourage",
"contemn":"to scorn, despise, or treat with contempt",
"contrariwise":"on the other hand, on the contrary",
"contrite":"deeply affected with grief and sorrow",
"convenient":"suitable, proper",
"conversant":"dwelling with",
"conversation":"behavior, conduct, or manner",
"convince":"to prove guilty, vanquish, refute",
"convocation":"an assembly",
"coriander":"plant with small spicy seeds",
"cormorant":"a large ravenous bird",
"corn":"a small hard particle of grain or seed",
"cotes":"a shelter for animals or storage",
"coulter":"blade of a plough",
"countenance":"appearance of the face",
"countervail":"a counterbalance",
"cousin":"kinsman, relative",
"covert":"a shelter or hiding place",
"cracknels":"light, crisp biscuits",
"crib":"the manger of a stable",
"crisping pins":"curling pins for a women's hair",
"crookbackt":"hump-backed, hunch-backed",
"cruse":"a small vessel for holding liquids",
"cubit":"cubit of a man, from elbow to fingertip; approx 18 in.",
"cuckow":"gull, bird",
"cumbered":"to overwhelm, trouble or burden",
"cummin":"a plant used as a spice",
"cunning":"skillful",
"curious":"detailed; intricately, or skillfully made",
"curious arts":"magic, sorcery",
"custom":"tribute, tax, toll",
"dainty":"delicate, pleasing, and valuable",
"dale":"a valley",
"dam":"a mother animal",
"damnation":"condemnation, judgment, or sentence",
"damned":"condemnation, judgment, or sentence",
"damsel":"a young unmarried woman or a girl",
"dandled":"danced on the knee; fondled",
"darling":"a term of endearment referring to a dearly loved person",
"dash":"<p><b>Dash</b>, To strike against; to beat towards",
"daub":"to cover, coat, or plaster",
"daysman":"a mediator, or arbitrator",
"dayspring":"day break; sunrise",
"deal":"a portion, share",
"dearth":"scarcity of rain; drought",
"deceivableness":"capable of being deceived",
"deck":"to adorn, cover or clothe",
"decline":"to deviate, or turn aside",
"delectable":"delightful, pleasing, or delicious",
"deliciously":"a manner to please or gratify",
"delightsome":"delightful, enjoyable, or pleasing",
"deputed":"to assign, commit, or authorize",
"deride":"to mock in ridicule, scorn, or contempt",
"describe":"divide, mark out",
"descry":"spy out, describe, or discover",
"despite":"contempt, scorn, or spite",
"devotions":"adoration, acts of worship, or praise",
"diadem":"royal head-dress",
"diet":"daily allowance",
"disannul":"to cancel, abolish, or nullify",
"discomfited":"to be defeated, overthrown, or frustrated",
"dispensation":"dealing out; distribution",
"disputation":"an argument, debate, discussion, or controversy",
"disquiet":"disturb, trouble, and make restless",
"dissembled":"to disguise, pretend, or act hypocritically",
"dissimulation":"to pretend, hypocrisy or deception",
"distil":"to drip or trickle down",
"divers":"different, diverse, varied",
"divination":"foretelling future events; discovering things secret",
"doctor":"teacher, instructor",
"doleful":"sorrowful, mournful, or grieved",
"dote":"to say or think foolishly",
"doting":"excessive fondness",
"downsitting":"sitting down",
"drams":"a weight of measure",
"draught":"to something derived or extracted ,  a privy, bathroom, or sewer",
"dromedary":"a one hump camel",
"duke":"a chief, commander, leader",
"dulcimer":"a stringed instrument",
"dung":"manure, excrement, or anything morally filthy",
"dureth":"to last, persist, endure, or continue in existence or state",
"durst":"dare",
"earing":"plough the ground,",
"eared":"plough the ground,",
"earnest":"serious, important, or zealous;  a pledge or deposit securing a contract",
"effeminate":"unmanly or unnaturally delicate, soft, or weak",
"emboldened":"to make bold",
"emerods":"hemorrhoids, swelling",
"eminent":"prominent, outstanding, or distinguished",
"emulation":"a jealous rivalry",
"endamage":"to inflict damage upon, injure, or discredit",
"endued":"to introduce, to bring to a certain condition",
"engines":"a mechanical device or machine; weapons of warfare",
"engrafted":"to be grafted in, inserted, implanted, or introduced",
"enjoin":"to direct, command, or impose",
"enlargement":"freedom, relief",
"ensample":"an example, pattern, model, or sample",
"ensign":"a signal, sign, token, emblem",
"ensue":"follow after",
"environ":"to surround, or to envelop",
"ephah":"about 8 gallons",
"ephod":"cape worn by priests",
"epistle":"A sent letter",
"ere":"before or until",
"eschew":"to shun, avoid, abstain from",
"espoused":"promised in marriage; betrothed; engaged",
"espy":"see, perceive",
"estate":"condition, position, or status",
"euroclydon":"a tempestuous north-easterly wind",
"evilfavouredness":"ugliness, deformity",
"exchanger":"money-changer; banker",
"execration":"a curse, detestation; abhorrence",
"fain":"gladly, willingly, or be content to",
"fairs":"anything gotten at a sale",
"familiar":"intimate, well acquainted, or in close association",
"farthing":"a fourth part of a penny",
"fat":"good, rich, full, prosperous",
"fats":"a vat or vessel",
"feebleminded":"to be weak, infirm, frail, or faint",
"feign":"to invent, pretend",
"felloes":"part of a wheel rim",
"fens":"a marsh or a bog",
"fetters":"shackles, metal bands",
"fillet":"an ornamental narrow band that goes around something",
"firkins":"a small wooden vessel or cask equal to one-fourth barrel",
"firmament":"the region of the air; the sky or heavens; or the sphere of the stars",
"firstling":"the first offspring of an animal",
"fitches":"an herb seed used as a spice or seasoning",
"flag":"an aquatic plant like a reed or rush",
"flagon":"a container for holding liquids",
"flanks":"the fleshy part of an animal between the ribs and the hip",
"flay":"to skin or strip off the skin",
"fleshhook":"a hook for fish",
"flowers":"the menstrual discharge",
"flux":"the flow of blood or any liquid discharge from the bowels",
"forbear":"to bear, endure, submit to, have patience with, tolerate",
"foreship":"the bow of a ship",
"forswear":"renounce earnestly, deny, or repudiate under an oath",
"forthwith":"immediately, at once, without delay",
"forum":"market place",
"forward":"eager, zealous, ready, or inclined to do something",
"foursquare":"square",
"frankly":"openly, freely",
"fray":"frighten, scare, terrify, or horrify",
"fret":"grieve, be angry",
"frontlets":"something worn on the forehead",
"froward":"stubborn, perverse, difficult, evil-disposed",
"furbish":"polish, sharpen",
"furlong":"220 yards",
"furniture":"equipment, harness",
"gaddest":"to move about restlessly or roam idly",
"gainsay":"to speak against, contradict, oppose, or hinder",
"gallant":"to be admirable, noble, finely dressed, or beautiful in appearance",
"garner":"a storehouse for grain, barn",
"gat":"got",
"gay":"happy, joyful, cheerful, or fine",
"gazingstock":"the object of someone's gaze or stare",
"gender":"to produce, breed, generate, or give rise to",
"gerah":"one twentieth of a shekel",
"gin":"a trap or snare",
"girdle":"belt",
"glass":"a mirror",
"glede":"a bird",
"glistering":"shining, sparkling, or glittering",
"godhead":"the trinity",
"goodman":"the male head of the household",
"greaves":"armor for the lower leg",
"grisled":"an animal that is gray colored, either whole or spotted",
"gross":"thick, powerful, or big",
"guile":"to deceive or trick",
"habergeon":"a sleeveless coat or jacket of armor",
"haft":"a handle",
"hale":"to draw, fetch, haul, or pull",
"hallow":"to make holy, consecrated, or set apart",
"halt":"lame or crippled",
"handmaid":"a female personal attendant, slave or servant",
"hap":"to happen by chance, or accident",
"hard":"close, near, or in close proximity",
"hardly":"with difficulty",
"hart":"a male deer",
"haunt":"a habit, custom, habitation, or place of frequent abode",
"heady":"to be headstrong, domineering, overbearing",
"heath":"open uncultivated land",
"helve":"a handle",
"hence":"from this time forward, from this place forward",
"highminded":"haughty, arrogant, or proud spirit",
"hin":"about 1.5 gallons",
"hind":"a female deer",
"hither":"to or towards, up to this point",
"hitherto":"until now, before",
"hoar":"old, aged, or white with age",
"holden":"held",
"holpen":"helped",
"homer":"10 ephahs or baths, about 80 gallons",
"hosanna":"\"save, we pray,\" a shout of praise",
"hosen":"articles of clothing to cover the legs",
"hough":"to disable by cutting the tendons in the hind leg",
"howbeit":"as it may, or nevertheless",
"husbandry":"the management of a household",
"ignominy":"dishonor, disgrace, or shame",
"immutable":"unchangeable, not liable to change, or variation",
"impenitent":"not repenting of sin; not contrite",
"imperious":"domineering, overbearing, dominant, or commanding",
"implacable":"unappeasable, or irreconcilable",
"implead":"to sue in a court of justice",
"importunity":"pressing solicitation; urgent request; unwanted persistence",
"impotent":"to be without power, helpless, weak or ineffective",
"impudent":"immodest, disrespectful, or shameless",
"impute":"To charge; to attribute or count",
"incontinent":"inability to contain or restrain oneself",
"inditing":"to declare something",
"infamy":"shame, disgrace, or bad reputation",
"infidel":"one who is unfaithful or unbelieving",
"infolding":"to envelop, enclose, contain, or fold in",
"injurious":"hurtful, insulting, abusive",
"inkhorn":"a small portable vessel for ink",
"inquisition":"investigation, examination, or inquiry",
"instant":"earnest, urgent or persistent",
"issue":"a discharge or flow from the body",
"jangling":"to make a harsh sound or a noisy altercation",
"jewry":"Judaea",
"jot":"a little bit or the very least part of something",
"kerchiefs":"a cloth used to cover the heads of women; veil",
"kernels":"the fruit seed, the inner part of a seed, or kernel of corn",
"kine":"cows",
"knop":"knob; anything that protrudes",
"lade":"to load; burden",
"lance":"spear",
"lancets":"a small spear, javelin, dart",
"lapwing":"a bird (a plover)",
"lasciviousness":"to be lustful, licentious, lewd",
"latchet":"thong, lace",
"laud":"to extol, praise, worship, or acclaim",
"laver":"a basin, bowl, or other vessel used for washing",
"leasing":"lying, falsehood, or deceit",
"leaven":"yeast, fermented bread dough",
"lees":"the deposits or sediment from a liquid; dregs",
"legion":"three to five thousand",
"leviathan":"aquatic animal; river or sea creature",
"libertines":"freed slaves",
"licence":"to give permission or authorization",
"lieutenants":"provincial rulers",
"lign aloes":"an aromatic wood",
"liking":"ones condition, whether good or bad",
"listed":"meaning pleases, desires",
"litters":"a portable couch or bed",
"lively":"living or to have life",
"lordly":"to be magnificent, noble, or grand",
"lowring":"gloomy, dark, threatening, or menacing",
"lucre":"dishonorable or unlawful gain or advantage",
"lunatick":"one who is insane",
"lusty":"vigorous, strong, lively or robust",
"magnifical":"renowned, glorious, eminent, stately",
"mail":"body armor of overlapping plates",
"malefactor":"a criminal, felon, or one who does evil",
"malignity":"hatred, wickedness, or malice",
"mallows":"an inedible plant",
"mammon":"reproach for wealth, riches, or money",
"mandrakes":"plant used as a love charm",
"mantle":"a loose sleeveless cloak",
"maranatha":"\"our Lord cometh.\"",
"marishes":"marshes, swamps or other wetlands",
"matrix":"the womb or the point of origin",
"maul":"hammer, mallet",
"maw":"stomach, the fourth stomach of a ruminant",
"mean":"common, undistinguished, inferior, or of low degree",
"meat":"food of any kind",
"meet":"to come together; proper, fitting, or becoming",
"mess":"a portion, share, ration, or allotment of food",
"messiah":"the anointed one",
"mete":"to allot, measure, or apportion",
"meteyard":"a measuring rod",
"milch":"an animal which gives milk",
"mincing":"with little steps",
"minish":"to make less in size, degree, power, or influence",
"mite":"extremely small piece of money",
"mitre":"a cap, turban, headdress; ceremonial headwear",
"mollified":"to be softened, soothed, appeased, or pacified",
"morrow":"the next day, the next morning",
"mortify":"to kill, destroy",
"mote":"a speck of dirt or dust",
"muffler":"an ornament worn by women",
"munition":"a fortification, defensive structure",
"murrain":"a plague effecting domestic animals",
"napkin":"a kerchief, neckerchief, handkerchief",
"nativity":"ones birth with reference to national identity",
"naught":"<p><b>Naught</b>, or Nought  worthless or nothing",
"naves":"the hub of wheels",
"necromancer":"one who attempts to foretell events by seeking the dead",
"neesings":"sneezing",
"nephew":"a grandson or descendant",
"nether":"lower; beneath",
"nigh":"near, proximity in place, time, or position",
"nitre":"carbonate of soda, a cleansing agent",
"noised":"to make a noise, spread a rumor, or report an event",
"noisome":"to be annoying or hurtful",
"obeisance":"an expression of respect or submission",
"oblation":"a sacrifice or offering usually made to a god",
"occupy":"to trade or do business",
"occurrent":"happening, taking place",
"odious":"offensive, disgusting, or repugnant",
"offend":"cause to stumble or sin",
"oft":"often; frequently",
"omer":"one tenth of an ephah, about 6:5 pints",
"omnipotent":"all-powerful; all-mighty",
"oracle":"someone regarded as infallible; a place",
"oration":"a prayer, speech or discourse",
"ordain":"to establish in a particular office or order",
"ossifrage":"a vulture",
"ouches":"sockets or precious settings",
"outgoings":"limits; boundaries",
"outlandish":"a foreigner, or one who is strange or bizarre",
"painfulness":"toil, labour",
"palsy":"paralysis",
"pangs":"sharp pains",
"paps":"nipples, breasts",
"paramours":"a mistress, concubine, or illicit lover",
"pate":"the crown of the head",
"patrimony":"an inheritance from one's father",
"peculiar":"singular, particular; belonging exclusively to a person",
"pentecost":"fiftieth day after passover",
"penury":"to be destitute or in poverty",
"peradventure":"perhaps; possibly",
"perdition":"damnation, destruction, or loss",
"pernicious":"destructive, hurtful, or wicked",
"phylacteries":"small boxes containing texts of Scripture",
"pilled":"to be peeled",
"plaiting":"to braid, fold together, or weave",
"plat":"plot of ground",
"platted":"to be braided or weaved",
"poll":"to count individually",
"polled":"cut hair",
"pommels":"a knob or ornamental ball",
"port":"gate, entry",
"post":"messenger carrying letters",
"potentate":"a sovereign, king, dictator, or supreme ruler",
"potsherd":"piece of broken pottery",
"pottage":"porridge, stew, or thick soup",
"pound":"a weight of silver",
"prating":"foolish, boastful, or vain talk",
"presbytery":"assembly of elders",
"presently":"immediately",
"press":"crowd of people",
"prevent":"to go before, or preceed",
"prevented":"to go before, or preceeded",
"prey":"booty, spoil",
"pricks":"goads for driving cattle",
"privily":"secretly; privately",
"privy":"to have knowledge of",
"profane":"common, unholy; to dishonor",
"progenitors":"ancestors or forefathers",
"prognosticators":"one who predicts, forecast, or foretells",
"proselyte":"convert to Judaism",
"prove":"to test or try",
"provender":"animal feed",
"psaltery":"a type of harp; stringed instrument",
"publican":"a tax collector",
"pulse":"grain, seed, or beans used as food",
"purloining":"stealing; theft",
"purtenance":"the intestines of an animal",
"putrifying":"to rot, decay; to stink",
"pygarg":"an antelope with a white rump",
"quarter":"a region, locality, or section",
"quaternions":"a set of four things",
"quicken":"to have, give, or restore life",
"quickeneth":"to have, give, or restore life",
"quit":"aquit; to be discharged or free ,  to release from an obligation",
"rail":"to denounce, scorn, insult",
"raiment":"clothing, dress, or apparel",
"rampart":"earth raised around a fort; fortification",
"ranging":"roving, wandering",
"rank":"full grown, upright, robust ,  to set the battle in array",
"rase":"demolish; destroy",
"ravening":"plundering; tearing to pieces",
"ravin":"to plunder, rob, or pillage",
"rear":"to raise, build or erect",
"redound":"to rebound, exceed, overflow",
"rehearse":"report, declare",
"reins":"the seat of emotions, feelings, or affections",
"rend":"to tear or pull apart",
"reprobate":"refused, depraved, worthless",
"requite":"to pay back or retaliate",
"rereward":"a rear guard",
"respite":"a rest, a reprieve or postponement",
"revellings":"a noisy feast, any kind of disorderly or immoral festivity",
"rifled":"to be plundered, robbed, pillaged",
"ringstraked":"streaked, striped",
"riot":"wanton, or wasteful living; extravagance",
"road":"a journey, hostile incursion, or raid",
"rude":"unlearned, uneducated, unskilled",
"rudiments":"first principles; origin, first form",
"rue":"an herb",
"sackbut":"a medieval wind instrument",
"sacrilege":"stealing what is consecrated to God",
"satiate":"to fill to excess or satisfy",
"satyr":"male goat",
"savour":"taste; think, understand",
"scall":"a sore or scab",
"scant":"skimped, meager",
"scrabbled":"rake, scrape, or snatch hurriedly",
"scrip":"a small bag, satchel, or purse",
"seemly":"fitting, proper or appropriate",
"seethe":"to boil or cook by boiling",
"selvedge":"the edge of woven fabric",
"sepulchre":"a tomb, grave, or burial place",
"servile":"befitting a slave or a menial position",
"servitor":"a servant, slave; one who provides a service",
"settle":"a sitting place, or a raised platform",
"severally":"separately, individually",
"shambles":"tables for displaying goods; market",
"shamefacedness":"the state or quality of being ashamed; modest",
"shekel":"about .5 ounce",
"sherd":"shard, fragment",
"shittim":"acacia tree",
"shivers":"chips, splinters, or slivers",
"shod":"wearing shoes or furnished with shoes",
"shroud":"cover, shelter",
"silly":"simple, foolish",
"silverlings":"a piece of money made of silver",
"similitude":"likeness, image, or resemblance",
"simple":"ignorant, without guile, innocent",
"sith":"since",
"sixscore":"120, 6 times 20",
"sleight":"an artful trick; cunning, or skill",
"slime":"mud, bitumen",
"sluices":"a dam for water; barrier",
"snuffed":"to inhale, draw up, smell",
"sod":"cook, boil",
"sodering":"soldering",
"sojourn":"dwell for a period",
"solace":"to comfort, sooth, console",
"soothsayer":"one who claims to foretell future events",
"sop":"bread dipped in liquid before being eaten",
"sottish":"to be foolish or stupid",
"spring":"dawn",
"stanched":"to stop",
"stead":"place",
"stomacher":"an embroidered garment; corset",
"straightway":"immediately or right away",
"strait":"to be narrow, tight, or close",
"strakes":"a streak or a stripe",
"strawed":"strewed, scattered",
"stripling":"a youth or young person",
"suborned":"to procure secretly, bribe, or obtain by corrupt or counterfeit means",
"subtil":"cunning; insight, perception",
"succour":"to help, aid, assist",
"sunder":"to separate, divide, or sever",
"sundry":"separate, various, or diverse",
"sup":"to have taken food to eat",
"superfluity":"to be excessive, overflowing, or unnecessary",
"supple":"to soften, easily bent",
"suppliants":"petition, pray, or beseech",
"surfeiting":"gluttony, overindulgence, or excess",
"surmisings":"allegations, suspicions, or suppositions",
"swaddling":"to wrap or bind with cloth",
"tabering":"the beating or striking of anything",
"tabernacle":"tent, dwelling",
"tablets":"ornaments, necklace, jewelry",
"taches":"fasteners; hooks",
"tale":"a number or quantity",
"talent":"OT: 3,000 shekels, 94 Lbs; NT: 60 pounds",
"tares":"any kind of weed",
"targets":"a small shield or buckler",
"teats":"the nipple on the breast",
"teil":"the linden or lime tree",
"tempt":"try, test",
"teraphim":"idols, images, or gods",
"terrestrial":"earthly, worldly; pertaining to land",
"tetrarch":"one of four rulers",
"thence":"from that time, date, or place",
"thither":"there, toward that place",
"thrice":"three times in succession",
"thyine":"wood from the thya tree",
"timbrel":"a small drum or tambourine",
"tire":"apparel, clothing, a head-dress",
"tithe":"a tenth",
"tittle":"the marks in writing",
"tow":"the fibers of flax",
"traffick":"to trade, engage in commerce",
"translate":"to transfer, convey, transport",
"travail":"work, labour",
"trespass":"sin, transgress",
"trow":"trust, believe, accept",
"turtle":"turtle-dove",
"twain":"two",
"twined":"to be twisted, wrapped, or plaited together",
"unawares":"unknowingly, unexpectedly",
"unction":"anointing; divine or sanctifying grace",
"untoward":"to be corrupt, improper, or perverse in the AV",
"upbraid":"to rebuke, condemn, or scold",
"usurp":"hold in possession without right",
"usury":"interest on money",
"uttermost":"outermost; last",
"vagabond":"fugitive, wanderer",
"vail":"curtain; divider",
"veil":"curtain; divider",
"vale":"a valley",
"valour":"importance, boldness, or determination",
"variableness":"changeable",
"variance":"dissension or controversy",
"vaunt":"to brag, boast, gloat",
"vehement":"vigorous, violent, or intense",
"vein":"a mineral deposit",
"venison":"the flesh of a beast of prey",
"venture":"a happening or event involving chance, risk",
"verily":"truly, really, or indeed",
"verity":"truth or an established fact",
"vermilion":"a bright red pigment",
"vestments":"garments, robes",
"vesture":"clothing or something that covers",
"vex":"to trouble, afflict, or agitate",
"vexation":"trouble, distress, affliction",
"victuals":"food, sustenance, or provisions",
"vile":"wicked; lowly; filthy",
"viol":"an instrument similar to a violin",
"virtue":"worth, goodness, morality",
"visage":"the face, countenance, or appearance of a person",
"wanton":"undisciplined, unruly, extravagant",
"wax":"growing or increasing in size or number",
"wayfaring":"a traveler or wanderer",
"waymarks":"guideposts",
"wen":"a lump, tumor, cyst",
"wench":"a young girl, a maid, or a young women",
"whence":"from what place",
"whet":"to sharpen",
"whit":"the least amount",
"wiles":"tricks, deceits, deception",
"wimples":"garment to cover the head and neck",
"wist":"knew",
"wit":"to know",
"withal":"therewith or with",
"withs":"cords, ropes",
"wont":"accustomed to, used to",
"wot":"know",
"wreathen":"twisting or interweaving",
"wrest":"to pull, force, detach",
"wroth":"angry, indignant, or incensed",
"yokefellow":"a person yoked or associated with another",
"yonder":"over there, that location",
"propitiation":"to appease or satisfy",
"reconciled":"to bring from enmity to friendship",
"reconciliation":"to bring from enmity to friendship",
"redemption":"to buy back",
"redeem":"to buy back",
"sanctify":"to set apart for God's use; to make holy",
"sanctified":"to set apart for God's use; to make holy",
"sanctifieth":"to set apart for God's use; to make holy",
"sanctification":"to set apart for God's use; to make holy",
"utter":"to send forth, as in speech",
"uttereth":"to send forth, as in speech",
"replenish":"fill abundantly; supply fully",
"addicted":"devoted",
"allow":"approve",
"fast":"secure; to not eat",
"sore":"intensely or severely; a bruise or ulcer",
"letteth":"allows or causes; hinders or prevents",
}